In [37]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import openpyxl

In [38]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
pd.set_option("display.precision", 2)

In [39]:
cad_data = pd.read_excel("./Municipal/Respostas/Formulario_1.xlsx", keep_default_na = True, header = 0, )
cad_data.head(3)

   uf nome_municipio  formulario  versao_salva  codigo_municipio                             v8957                                           v9843                               v8959                                              v8958 v13807                   v13808             v13809                                         v13810                             v9844                                          v13736                       v8961 v8962                                              v8963          v8964        v8965 v8966                            v8967           v8968           v9845                                             v13816                                             v13817     usuario     data_hora_preenchimento            data_hora_extracao
0  AC    Mâncio Lima         1.1         16321           1200336                Sâmela Silva Moura      Secretaria Municipal de Assistência Social  Departamento de Assistęncia Social                                   Assessoria Geral      1    Ensino médio completo   Entre 1 a 2 anos  Năo atua no âmbito da SAN na gestăo municipal         Rocilda da Costa Mendonça                                      Secretária  R Francisca Alves Ferreira   S/N  Em frente a uma oficina mecânica; Ao lado da p...   José Martins  Mâncio Lima    AC               semasml@hotmail.cm   (68) 33431674             NaN                                          Por email  O município năo participou do MapaSAN em nenhu...  5407811260  2022-07-27 11:54:12.606714  2022-08-15 13:59:47.49906-03
1  AC     Porto Acre         1.1         25737           1200807  Francisco Geronimo Lopes Fortes                Secretaria de assistência social                              Gestăo                        Coordenaçăo Municipal do PAB     12    Ensino médio completo  Há mais de 8 anos  Năo atua no âmbito da SAN na gestăo municipal                 Daiany Gonçalves                            Secretaria municipal        Avenida  Chico rabelo    Sn                              Prefeitura municipal         Centro    Porto Acre    AC           smaas_pa8@yahoo.com.br   (68) 32331011   (68) 32331011                                              Imail  O município participou do MapaSAN em uma ou ma...   122911296  2022-08-11 20:35:23.906333  2022-08-15 13:59:47.49906-03
2  AL      Arapiraca         1.1          5642           2700300       ANA CRISTINA XAVIER ALMEIDA  SECRETARIA MUNICIPAL DE DESENVOLVIMENTO SOCIAL                 SEGURANÇA ALIMENTAR  COORDENADORA DA SEGURANÇA ALIMENTAR - NUTRICIO...     15  Especializaçăo completa  Há mais de 8 anos                              Há mais de 8 anos  FABRÍCIA SILVA DE ARAÚJO GALINDO  SECRETÁRIA MUNICIPAL DE DESENVOLVIMENTO SOCIAL              RUA SAMARITANA  1185                                                  -  SANTA EDWIGES    Arapiraca    AL  SMDS@GESTAO.ARAPIRACA.AL.GOV.BR  (82) 999156171  (82) 996457382  E-MAIL RECEBIDO PELA VIGILÂNCIA SOCIOASSISTENC...  O município participou do MapaSAN em uma ou ma...  4907739400   2022-06-28 10:36:38.39242  2022-08-15 13:59:47.49906-03

In [40]:
cad_data.dtypes

uf                          object
nome_municipio              object
formulario                 float64
versao_salva                 int64
codigo_municipio             int64
v8957                       object
v9843                       object
v8959                       object
v8958                       object
v13807                      object
v13808                      object
v13809                      object
v13810                      object
v9844                       object
v13736                      object
v8961                       object
v8962                       object
v8963                       object
v8964                       object
v8965                       object
v8966                       object
v8967                       object
v8968                       object
v9845                       object
v13816                      object
v13817                      object
usuario                     object
data_hora_preenchimento     object
data_hora_extracao          object
dtype: object

In [41]:
cad_data["codigo_municipio"].count()

2053

In [42]:
cad_data['uf'].value_counts()

PR    348
SP    250
MG    221
CE    169
BA    114
PA    106
RS    105
SC     93
PB     82
TO     81
MA     74
SE     60
AM     54
PE     51
RJ     37
RN     36
ES     36
GO     34
PI     26
MS     21
MT     17
AL     16
RR     10
RO      8
AP      2
AC      2
Name: uf, dtype: int64

In [43]:
df_uf = pd.DataFrame(cad_data['uf'].value_counts())
df_uf['percentual'] = (cad_data["uf"].value_counts()/cad_data["uf"].value_counts().sum())*100
df_uf

     uf  percentual
PR  348       16.95
SP  250       12.18
MG  221       10.76
CE  169        8.23
BA  114        5.55
PA  106        5.16
RS  105        5.11
SC   93        4.53
PB   82        3.99
TO   81        3.95
MA   74        3.60
SE   60        2.92
AM   54        2.63
PE   51        2.48
RJ   37        1.80
RN   36        1.75
ES   36        1.75
GO   34        1.66
PI   26        1.27
MS   21        1.02
MT   17        0.83
AL   16        0.78
RR   10        0.49
RO    8        0.39
AP    2        0.10
AC    2        0.10

In [44]:
file = "estimativa_dou_2021.xls"
mun = pd.read_excel(file, sheet_name='Municípios')
mun

            Região  UF  COD. UF  COD. MUNIC  CODIGO7  CODIGO6      NOME DO MUNICÍPIO  POPULAÇÃO ESTIMADA Porte populacional IBGE   Porte Populacional II
0            Norte  RO       11          15  1100015   110001  Alta Floresta D'Oeste               22516    De 20.001 até 50.000              Até 50.000
1            Norte  RO       11          23  1100023   110002              Ariquemes              111148  De 100.001 até 500.000  De 100.001 até 200.000
2            Norte  RO       11          31  1100031   110003                 Cabixi                5067     De 5.001 até 10.000              Até 50.000
3            Norte  RO       11          49  1100049   110004                 Cacoal               86416   De 50.001 até 100.000   De 50.001 até 100.000
4            Norte  RO       11          56  1100056   110005             Cerejeiras               16088    De 10.001 até 20.000              Até 50.000
...            ...  ..      ...         ...      ...      ...                    ...                 ...                     ...                     ...
5565  Centro-Oeste  GO       52       22005  5222005   522200             Vianópolis               14088    De 10.001 até 20.000              Até 50.000
5566  Centro-Oeste  GO       52       22054  5222054   522205         Vicentinópolis                9002     De 5.001 até 10.000              Até 50.000
5567  Centro-Oeste  GO       52       22203  5222203   522220               Vila Boa                6451     De 5.001 até 10.000              Até 50.000
5568  Centro-Oeste  GO       52       22302  5222302   522230          Vila Propício                5941     De 5.001 até 10.000              Até 50.000
5569  Centro-Oeste  DF       53         108  5300108   530010               Brasília             3094325         Mais de 500.000         Mais de 500.000

[5570 rows x 10 columns]

In [49]:
mun_uf= mun['UF'].value_counts()
mun_uf = pd.DataFrame(mun_uf)
mun_uf.columns = ['tot_mun']
mun_uf

    tot_mun
MG      853
SP      645
RS      497
BA      417
PR      399
SC      295
GO      246
PI      224
PB      223
MA      217
PE      185
CE      184
RN      167
PA      144
MT      141
TO      139
AL      102
RJ       92
MS       79
ES       78
SE       75
AM       62
RO       52
AC       22
AP       16
RR       15
DF        1

In [56]:
mun_resp = df_uf.merge(mun_uf, left_index=True, right_index=True)
mun_resp.columns = ['mun_resp', 'perc_resp', 'mun_tot']
mun_resp['perc_tot'] = (mun_resp['mun_resp']/mun_resp[ 'mun_tot'])*100
mun_resp

    mun_resp  perc_resp  mun_tot  perc_tot
PR       348      16.95      399     87.22
SP       250      12.18      645     38.76
MG       221      10.76      853     25.91
CE       169       8.23      184     91.85
BA       114       5.55      417     27.34
PA       106       5.16      144     73.61
RS       105       5.11      497     21.13
SC        93       4.53      295     31.53
PB        82       3.99      223     36.77
TO        81       3.95      139     58.27
MA        74       3.60      217     34.10
SE        60       2.92       75     80.00
AM        54       2.63       62     87.10
PE        51       2.48      185     27.57
RJ        37       1.80       92     40.22
RN        36       1.75      167     21.56
ES        36       1.75       78     46.15
GO        34       1.66      246     13.82
PI        26       1.27      224     11.61
MS        21       1.02       79     26.58
MT        17       0.83      141     12.06
AL        16       0.78      102     15.69
RR        10       0.49       15     66.67
RO         8       0.39       52     15.38
AP         2       0.10       16     12.50
AC         2       0.10       22      9.09